import localFont from "next/font/local";
import "./globals.css";
import { Github } from "lucide-react";
import Link from "next/link";
import { motion } from "framer-motion";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="absolute top-0 right-0 z-10 p-4">
          <Link href="https://github.com/SammuelChang" target="_blank">
            <Github />
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
